model_list:
  - model_name: qwen-local
    litellm_params:
      model: ollama/qwen2.5-coder:0.5b
      api_base: http://localhost:11434
  - model_name: qwen-local-3b
    litellm_params:
      model: ollama/qwen2.5-coder:3b
      api_base: http://localhost:11434    

litellm_settings:
  callbacks: ["otel"]
  drop_params: true
  stream: true  

general_settings:
  master_key: sk-master-1234
  database_connection_pool_limit: 10
  database_connection_timeout: 60
  disable_spend_logs: false
  health_check_interval: 120
  use_client_credentials_from_environment_variables: true
  database_url: "postgresql://postgres:Password123@127.0.0.1:5432/litellm?pool_timeout=60&connection_limit=10"